### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by tonyspanos** [Adam-Software/Feetech-Servo-SDK#1]
Hi! 
I would like to first of all thank you for making the software available. Could you explain how the servo could be wired to a raspberry pi? A diagram would help.

Thank you very much!

**Comment by vertigra** [comment]
Hi!
You can use the [official guide](https://github.com/Adam-Software/Feetech-Servo-SDK/files/11502889/start.tutorial201015.pdf)  to connect in a way that is convenient for you

**Comment by vertigra** [comment]
We use this method


![this ](https://github.com/Adam-Software/Feetech-Servo-SDK/assets/1764907/ebbade70-9916-42c1-9c48-ce6b844604d6)
